Description: Test
Parameters:
  Cake:
    Type: String
    Description: The object of our desires
    AllowedPattern: ^[a-z]+$
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [the, !Ref 'Cake', is, a, lie]]
Outputs:
  BucketDomain:
    Value: !GetAtt [Bucket, DomainName]
